# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RX_TEST' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa' 
  pod 'RxDataSources'
  pod 'RxAtomic'

  # Pods for RX_TEST

end
